plugins: jemoji
  html { 
  background: (https://github.com/kortana80/design/blob/master/FeliciaRodriguez_StillLife.jpg) no-repeat center center fixed; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
theme: jekyll-theme-architect
title: Kortana80

